version: "2.2"
services:
  mgwdb:
    image: postgres:14.1-alpine
    container_name: mgwdb-db
    restart: always
    environment:
      - POSTGRES_USER=mgwdb
      - POSTGRES_PASSWORD=mgwdb
      - APP_DB_USER=mgwdb
      - APP_DB_PASS=mgwdb
      - APP_DB_NAME=mgwdb
    ports:
      - '5433:5432'
    networks:
      - mgwdbnet
    volumes:
      - ./db-data/:/var/lib/postgresql/data

networks:
  mgwdbnet:
    driver: bridge